#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
volumeicon &
cbatticon -u 60 -i standard -l 15 &
redshift-gtk &
urxvtd -q -o -f

# X settings
xrdb ~/.Xresources

# xscreensaver lock
xscreensaver -no-splash &
xss-lock -- xscreensaver-command --lock &

# X fonts
# fonts
xset +fp ~/.fonts/tamsyn
xset +fp ~/.fonts/ubuntu-font
xset fp rehash

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/savorn/.fluxbox/log"
