" Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
call vundle#end()

syntax enable
set autoindent
filetype plugin indent on
set hidden
set showcmd
set showmatch
set incsearch
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set number
set cursorline
set background=light

set tabstop=4
set softtabstop=4

" GVim settings
set guioptions-=T "remove toolbar
set guioptions-=r "remove right-hand scroll bar
set guioptions-=L "remove left-hand scroll bar
set guifont=Fira\ Mono\ Medium\ 11

" colorscheme
colorscheme PaperColor
