# start up applications
redshift &

# xscreensaver lock screen
xscreensaver -nosplash &
xss-lock -- xscreensaver-command -lock &

# URxvt daemon
urxvtd -q -o -f

# load X resources
xrdb ~/.Xresources

# allow fonts in X server
xset +fp ~/.fonts/gohufont
xset +fp ~/.fonts/ttf
xset +fp /usr/share/fonts/opentype/font-awesome
xset fp rehash

# execute window manager
exec i3
