# start up applications
redshift-gtk &
blueman-applet &

# xscreensaver lock screen
xscreensaver -nosplash &
xss-lock -- xscreensaver-command -lock &

# load wallpaper using feh
sh ~/.fehbg

# URxvt daemon
urxvtd -q -o -f

# load X resources
xrdb ~/.Xresources

# allow fonts in X server
xset +fp ~/.fonts/gohufont
xset +fp ~/.fonts/ttf
xset +fp ~/.fonts/bdf
xset fp rehash

# execute window manager
exec i3
