# set wallpaper
sh ~/.fehbg

# xscreensaver daemon
xscreensaver -no-splash &

# screen lock
xss-lock -- xscreensaver-command -lock &

# trackpoint settings
xinput set-prop "ETPS/2 Elantech TrackPoint" "Device Accel Constant Deceleration" 0.4
xinput set-prop "ETPS/2 Elantech TrackPoint" "Evdev Wheel Emulation" 1
xinput set-prop "ETPS/2 Elantech TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5
xinput set-prop "ETPS/2 Elantech TrackPoint" "Evdev Wheel Emulation Button" 2

# keybinds
xbindkeys

# urxvt daemon
urxvtd -q -o -f

# change color temperature for day and night
redshift -l 35:-80 &

# fonts for X
xset +fp ~/.fonts/tamsyn
xset +fp ~/.fonts/Sourcecode
xset fp rehash

# turn beep off
xset b off

# load X resources
xrdb ~/.Xresources

# dwm status script
~/bin/dwmstatus.sh

# start windows manager
exec dwm
